apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260610-224618-8qpoc65wphb3-service
spec:
  selector:
    app: enterprise-system-20260610-224618-8qpoc65wphb3
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
